/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/mastercardTheme.ts
 * Command: astryx theme build src/mastercardTheme.ts --out src/mastercard-theme.css
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/**
 * mastercard theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { mastercardTheme } from './mastercard';
 *   import './mastercard.css';
 */
export const mastercardTheme = {
  name: 'mastercard',
  __built: true,
  tokens: {
    "--font-family-body": "\"Sofia Sans\", Arial, \"Helvetica Neue\", sans-serif",
    "--font-family-heading": "\"Sofia Sans\", Arial, \"Helvetica Neue\", sans-serif",
    "--color-background-body": "light-dark(#F3F0EE, #141413)",
    "--color-background-card": "light-dark(#FCFBFA, #1C1C1A)",
    "--color-background-surface": "light-dark(#FCFBFA, #262625)",
    "--color-background-muted": "light-dark(#F4F4F4, #262625)",
    "--color-accent": "light-dark(#141413, #F3F0EE)",
    "--color-accent-muted": "light-dark(#F4F4F4, #262625)",
    "--color-on-accent": "light-dark(#F3F0EE, #141413)",
    "--color-text-accent": "light-dark(#141413, #F3F0EE)",
    "--color-icon-accent": "light-dark(#141413, #F3F0EE)",
    "--color-neutral": "light-dark(rgba(20, 20, 19, 0.06), rgba(252, 251, 250, 0.08))",
    "--color-overlay": "light-dark(rgba(20, 20, 19, 0.55), rgba(0, 0, 0, 0.72))",
    "--color-overlay-hover": "light-dark(rgba(20, 20, 19, 0.05), rgba(252, 251, 250, 0.07))",
    "--color-overlay-pressed": "light-dark(rgba(20, 20, 19, 0.1), rgba(252, 251, 250, 0.12))",
    "--color-text-primary": "light-dark(#141413, #F3F0EE)",
    "--color-text-secondary": "light-dark(#696969, #B0AAA2)",
    "--color-text-disabled": "light-dark(#D1CDC7, #565656)",
    "--color-icon-primary": "light-dark(#141413, #F3F0EE)",
    "--color-icon-secondary": "light-dark(#696969, #B0AAA2)",
    "--color-icon-disabled": "light-dark(#D1CDC7, #565656)",
    "--color-border": "light-dark(rgba(20, 20, 19, 0.1), rgba(252, 251, 250, 0.12))",
    "--color-border-emphasized": "light-dark(rgba(20, 20, 19, 0.35), rgba(252, 251, 250, 0.4))",
    "--color-skeleton": "light-dark(#E8E2DA, #2A2A28)",
    "--color-shadow": "light-dark(rgba(0, 0, 0, 0.08), rgba(0, 0, 0, 0.4))",
    "--color-tint-hover": "light-dark(black, white)",
    "--shadow-low": "light-dark(rgba(20, 20, 19, 0.04) 0px 2px 8px, rgba(0, 0, 0, 0.3) 0px 2px 8px)",
    "--shadow-med": "light-dark(rgba(20, 20, 19, 0.06) 0px 12px 32px, rgba(0, 0, 0, 0.35) 0px 12px 32px)",
    "--shadow-high": "light-dark(rgba(0, 0, 0, 0.08) 0px 24px 48px, rgba(0, 0, 0, 0.45) 0px 24px 48px)",
    "--color-background-orange": "light-dark(#F9DCCB, rgba(243, 115, 56, 0.16))",
    "--color-border-orange": "light-dark(#E8A177, rgba(243, 115, 56, 0.45))",
    "--color-icon-orange": "light-dark(#CF4500, #F37338)",
    "--color-text-orange": "light-dark(#9A3A0A, #F9A47C)",
    "--radius-element": "20px",
    "--radius-container": "40px",
    "--radius-inner": "999px"
  },
  components: {
    "button": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "letterSpacing": "-0.02em",
        "fontWeight": "500"
      }
    },
    "badge": {
      "base": {
        "borderRadius": "var(--radius-full)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
