/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/mastercardTheme.ts
 * Command: astryx theme build src/mastercardTheme.ts --out src/mastercard-theme.css
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const mastercardTheme: DefinedTheme;
